# Generated by Django 5.1.4 on 2025-01-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mail', models.EmailField(max_length=250)),
                ('phno', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('university', models.CharField(max_length=250)),
            ],
        ),
    ]
