# Generated by Django 5.1.4 on 2025-01-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userform',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
